package cc.wecando.harmoniousfamily.backend

import cc.wecando.harmoniousfamily.backend.plugins.Alert
import cc.wecando.harmoniousfamily.backend.plugins.AntiRevoke
import cc.wecando.harmoniousfamily.backend.plugins.Message
import cc.wecando.harmoniousfamily.backend.plugins.Xml


/**
 * Dynamically generated by build.gradle
 */
val WechatPlugins = listOf(Alert, Message, Xml, AntiRevoke)
