package cc.wecando.harmoniousfamily.backend

import com.gh0u1l5.wechatmagician.spellbook.interfaces.IXmlParserHook


/**
 * Dynamically generated by build.gradle
 */
val WechatPlugins = emptyList<IXmlParserHook>()
