package cc.wecando.harmoniousfamily.backend

import cc.wecando.harmoniousfamily.backend.plugins.*


/**
 * Dynamically generated by build.gradle
 */
val WechatPlugins = listOf(Alert, Message, Xml, AntiRevoke, Game)
